[versions]
agp = "8.7.2"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.9.3"
composeBom = "2024.04.01"
navigationCompose = "2.8.4"
navigationRuntimeKtx = "2.8.4"
translate = "17.0.3"
firebaseBom = "33.7.0"
mlkit-language-id = "17.0.3"
mlkit-translate = "17.0.3"
firebase-analytics = "21.3.0"
languageIdCommon = "16.1.0"
uiTextGoogleFonts = "1.7.6"
material3 = "1.3.1"

[libraries]
firebase-database = { module = "com.google.firebase:firebase-database" }
google-ml-kit = "com.google.mlkit:text-recognition:16.0.0"
androidx-camera-core = "androidx.camera:camera-core:1.4.0"
androidx-camera-camera2 = "androidx.camera:camera-camera2:1.4.0"
androidx-camera-lifecycle = "androidx.camera:camera-lifecycle:1.4.0"
androidx-camera-view = "androidx.camera:camera-view:1.4.0"
androidx-camera-extensions = "androidx.camera:camera-extensions:1.4.0"
coil-compose = "io.coil-kt:coil-compose:2.4.0"
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
translate = { group = "com.google.mlkit", name = "translate", version.ref = "translate" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
mlkit-language-id = { module = "com.google.mlkit:language-id", version.ref = "mlkit-language-id" }
mlkit-translate = { module = "com.google.mlkit:translate", version.ref = "mlkit-translate" }
language-id-common = { group = "com.google.mlkit", name = "language-id-common", version.ref = "languageIdCommon" }
androidx-ui-text-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

